# Generated by Django 4.2.2 on 2023-08-06 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_category_prod_product_cat_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat_prod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.category_prod', verbose_name='Категория товара'),
        ),
    ]
