# Generated by Django 4.2.5 on 2023-09-24 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
