# Generated by Django 4.2.5 on 2023-09-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_product_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="news_images/%Y/%m/%d", verbose_name="Изображение"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to="store_images/%Y/%m/%d",
                verbose_name="Картинка товара",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="publication_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата публикации"
            ),
        ),
    ]
