# Generated by Django 4.2.5 on 2023-09-29 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0013_alter_news_image_alter_product_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="cat_prod",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="main.category_prod",
                verbose_name="Категория товара",
            ),
        ),
    ]
