# Generated by Django 4.2.5 on 2023-09-24 20:48

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_profile_contract_number_alter_profile_photo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=account.models.user_directory_path
            ),
        ),
    ]
